### PR TITLE
for livekitroom: custom styles, custom labels and click property for …

### PR DESCRIPTION
**Pull request by AlpMehmet**
…particapant

### CODE REVIEW

**Review by davidzhao — COMMENTED** [review]
I don't think this is the direction that we want to go.

The built in ParticipantView is provided as an example, and for folks to build their own applications using it as a guide.

Offering up these UI options make it more confusing to a user, and we would not be able to achieve the flexibility that comes with providing their own stage rendering.

**Comment by metiftikci** [comment]
```jsx
  <ControlRenderer
    ...
    classNames={{
      endButton: "end-button",
      endButtonPopover: "end-button-popover",
      ...
    }}
    labels={{
      shareScreen: t("shareScreen"),
      stopShare: t("stopShare"),
      ...
    }}
  />
```

@davidzhao what about wrap settings like above?

We are using this library in production. We did not want to fork. Instead improve/add new features to original repo, then anyone can use and improve.

It would be nice to have a repo which is customizable and usable easily. (Most important things for us `internationalization` and `custom styles`)

We also want to add modes like `click to show participant in front (large)`.

If you are planing this repo as example, i'm suggesting a new repo for example named `livekit-react-example` with minimum settings or `New Repo As React SDK` to use in production directly with more options and features.

**Comment by AlpMehmet** [comment]
@davidzhao ping

**Comment by davidzhao** [comment]
You don't have to fork the repo at all to achieve customizations. Please see https://github.com/livekit/livekit-react#customize-rendering for details.

Our [playground](https://livekit.io/playground) takes this approach, it builds its own customized Stage renderer and passes that in.

Adding options like this PR does will increase its customizability, but also increases the complexity significantly. What we are striving for is to keep the basics simple, but offering folks an easy way to swap out various components during rendering.

**Pull request closed without merging**
