### PR TITLE
Add option to not request media permissions for select buttons

### LINKED ISSUE #88: Question: About getting camera privileges
Hi, I have a question on the interaction, if I want to turn off the camera permission acquisition at the first time, is there an api method to achieve it?

https://example.livekit.io/

### PR DESCRIPTION
**Pull request by lukasIO**
closes #88

### CODE REVIEW

**Comment by WuChenDi** [comment]
@lukasIO 
Hi guys, I raised a question [here](https://github.com/livekit/livekit-react/issues/88). I see that you are responding quickly to the processing. 
That's great.
But I think you could handle it with the `isEnabled` field, which would avoid opening a new variable.

I also have a new question, is it possible to add this processing to the `LiveKitRoom` component as well, under the `/room` route.

Looking forward to your response, thanks!

**Comment by lukasIO** [comment]
hi @WuChenDi,

there's two things at play here: the camera and microphone select buttons ask for user media permissions by default in order to enumerate the devices, this PR gives users the option to explicitly turn this behaviour off. 
the other part is the preview of the camera. If you want to avoid showing video by default, then you are right, you could just disable video by default on the PreJoinPage by commenting out this section
https://github.com/livekit/livekit-react/blob/master/example/src/PreJoinPage.tsx#L47-L55

If you want to change the routing behaviour or rather when to setup devices, you can of course do so.

**Comment by WuChenDi** [comment]
@lukasIO  Thank you for your reply.
Yes, I found this problem when I was debugging locally, `createLocalVideoTrack` will also request camera and microphone permissions.
Now I have a new question, in this [example](https://example.livekit.io/), when I click `connect` to enter the `room` page, I need camera and microphone permission by default, can I also provide configuration items here. For example, I don't need camera access by default, I see the code here.

https://github.com/livekit/livekit-react/blob/master/example/src/RoomPage.tsx#L89

**Comment by lukasIO** [comment]
Here's the part that enables the camera on the room page: 
https://github.com/livekit/livekit-react/blob/master/example/src/RoomPage.tsx#L128-L135

Feel free to join the LiveKit community slack if you have further questions: https://join.slack.com/t/livekit-users/shared_invite/zt-19nswkhip-4Y56hpIHM94EyWUpRH1GGQ

**Review by davidzhao — APPROVED** [review]
lgtm!

**Pull request merged**
